EXTENSION_TO_TREE_SITTER_LANGUAGE = {
    ".c": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".cs": "c-sharp",
    ".cxx": "cpp",
    ".go": "go",
    ".hs": "haskell",
    ".java": "java",
    ".jl": "julia",
    ".js": "javascript",
    ".jsx": "javascript",
    ".php": "php",
    ".py": "python",
    ".rb": "ruby",
    ".rs": "rust",
    ".scala": "scala",
    ".sql": "sql",
    ".swift": "swift",
    ".ts": "typescript",
    ".tsx": "typescript",
}
